spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 480ea2f06f68ac1b02f9
            client-secret: 9e54d0f8b2504418ac25b9e787d43db9198963aa
            scope: name,email,avatar_url

          naver:
            client-id: UPWVG_Gio27XCh2RqtXW
            client-secret: xmXuY44SHd
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: name,email
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response